import { ChecklistItem, PracticeMgmtStatus, CalendarSlot, AuditLogEntry, ClientProfile, NotificationRule } from '../types/vera';

export const INITIAL_CLIENT_PROFILE: ClientProfile = {
  id: 'cli_elena_rostova',
  fullName: 'Elena Rostova',
  email: 'elena.rostova@designlab.io',
  phone: '+1 (415) 892-3401',
  firmName: 'Sterling & Vance CPAs LLP',
  firmAddress: '100 Montgomery St, Suite 1800, San Francisco, CA 94104',
  taxYear: '2025 / 2026',
  mfaEnabled: true,
  mfaMethod: 'authenticator_app',
  eSignedEngagementLetter: true,
  eSignedDate: '2026-02-18T10:14:22Z',
  eSignedHash: 'SHA256: 4f9812e987cba124803da912fbb710c',
  section7216ConsentSigned: true,
  onboardingStep: 4, // 4 = completed, but can view or reset
};

export const INITIAL_CHECKLIST: ChecklistItem[] = [
  // Income
  {
    id: 'doc-w2-apex',
    title: 'Form W-2: Primary Wages',
    category: 'income',
    description: 'Wage & Tax Statement from your primary employer (Box 1 wages & Box 2 federal tax withheld).',
    required: true,
    status: 'uploaded',
    uploadedFileName: '2025_W2_Apex_Technologies.pdf',
    uploadedFileSize: '1.4 MB',
    uploadedAt: '2026-03-02T16:20:00Z',
    storageHash: 'AES256: 8a1f49e019cd',
    ocrData: {
      documentType: 'Form W-2',
      issuerName: 'Apex Technologies LLC',
      taxYear: '2025',
      ein: 'XX-XXX4912',
      wagesOrAmount: '$112,500.00',
      taxWithheld: '$18,400.00',
      confidenceScore: 0.99,
    },
  },
  {
    id: 'doc-1099-nec-consulting',
    title: 'Form 1099-NEC: Consulting & Advisory',
    category: 'income',
    description: 'Nonemployee Compensation from freelance clients or design consulting.',
    required: true,
    status: 'uploaded',
    uploadedFileName: '1099NEC_StudioVeloce_2025.pdf',
    uploadedFileSize: '890 KB',
    uploadedAt: '2026-03-08T11:45:00Z',
    storageHash: 'AES256: 3c910fa89b12',
    ocrData: {
      documentType: 'Form 1099-NEC',
      issuerName: 'Studio Veloce Inc.',
      taxYear: '2025',
      wagesOrAmount: '$24,800.00',
      taxWithheld: '$0.00',
      confidenceScore: 0.97,
    },
  },
  {
    id: 'doc-1099-div-vanguard',
    title: 'Form 1099-DIV / 1099-B: Investments',
    category: 'income',
    description: 'Consolidated brokerage statement showing dividends, capital gains/losses, and foreign tax paid.',
    required: false,
    status: 'uploaded',
    uploadedFileName: 'Vanguard_1099_Consolidated_2025.pdf',
    uploadedFileSize: '2.1 MB',
    uploadedAt: '2026-03-12T14:10:00Z',
    storageHash: 'AES256: 77b4c91902ae',
    ocrData: {
      documentType: 'Form 1099-DIV/B',
      issuerName: 'Vanguard Group Inc',
      taxYear: '2025',
      wagesOrAmount: '$3,420.00 Ordinary Div',
      confidenceScore: 0.96,
    },
  },

  // Deductions
  {
    id: 'doc-1098-mortgage',
    title: 'Form 1098: Mortgage Interest Statement',
    category: 'deductions',
    description: 'Mortgage interest paid (Box 1), real estate property taxes, and outstanding mortgage principal.',
    required: true,
    status: 'missing',
  },
  {
    id: 'doc-charity-receipts',
    title: 'Charitable Contribution Receipts',
    category: 'deductions',
    description: 'Written acknowledgments for donations $250+ to 501(c)(3) non-profit organizations.',
    required: false,
    status: 'uploaded',
    uploadedFileName: 'Charity_StJude_RedCross_2025.pdf',
    uploadedFileSize: '640 KB',
    uploadedAt: '2026-03-14T09:30:00Z',
    storageHash: 'AES256: db92110c71a3',
    ocrData: {
      documentType: 'Donation Acknowledgement',
      issuerName: 'St. Jude Children Research & Red Cross',
      taxYear: '2025',
      wagesOrAmount: '$1,850.00 Total',
      confidenceScore: 0.94,
    },
  },
  {
    id: 'doc-1099-sa-hsa',
    title: 'Form 1099-SA / 5498-SA: Health Savings Account',
    category: 'deductions',
    description: 'Distributions and annual contributions made to your HSA plan.',
    required: false,
    status: 'missing',
  },

  // Business (Schedule C)
  {
    id: 'doc-sched-c-pl',
    title: 'Annual Profit & Loss (P&L) or Expense Summary',
    category: 'business',
    description: 'Categorized business receipts, software subscriptions, travel, and home office costs.',
    required: true,
    status: 'missing',
  },
  {
    id: 'doc-mileage-log',
    title: 'Business Mileage Log',
    category: 'business',
    description: 'Contemporaneous log of business miles driven (standard IRS rate ~67¢/mile).',
    required: false,
    status: 'missing',
  },

  // Prior Year & Identity
  {
    id: 'doc-id-license',
    title: 'Government-Issued Photo ID (Driver’s License / Passport)',
    category: 'prior_year',
    description: 'IRS Identity Protection requirement for electronic filing (MeF identity verification).',
    required: true,
    status: 'uploaded',
    uploadedFileName: 'CA_Drivers_License_Front_Back.pdf',
    uploadedFileSize: '1.1 MB',
    uploadedAt: '2026-02-18T10:18:00Z',
    storageHash: 'AES256: fe0821bca981',
    ocrData: {
      documentType: 'State ID / Driver License',
      issuerName: 'State of California DMV',
      confidenceScore: 0.99,
    },
  },
  {
    id: 'doc-prior-tax-return',
    title: 'Prior Year Form 1040 (Tax Year 2024)',
    category: 'prior_year',
    description: 'Last year’s federal & California return to verify carryforwards, depreciation schedules, and AGI.',
    required: true,
    status: 'uploaded',
    uploadedFileName: '2024_Form_1040_Signed.pdf',
    uploadedFileSize: '3.8 MB',
    uploadedAt: '2026-02-18T10:20:00Z',
    storageHash: 'AES256: aa192305bf99',
    ocrData: {
      documentType: 'Form 1040 Return',
      taxYear: '2024',
      issuerName: 'Department of the Treasury - IRS',
      confidenceScore: 0.98,
    },
  },
];

export const INITIAL_PRACTICE_MGMT_STATUS: PracticeMgmtStatus = {
  systemProvider: 'Karbon',
  clientId: 'cli_elena_rostova',
  clientName: 'Elena Rostova',
  assignedPreparer: {
    name: 'Marcus Vance, CPA',
    title: 'Senior Partner & Practice Lead',
    email: 'marcus.vance@sterlingvancecpa.com',
    phone: '+1 (415) 790-2200 ext. 104',
    licenseNumber: 'CPA-CA-098231',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  },
  taxYear: '2025 / 2026',
  returnType: 'Form 1040 (Individual)',
  overallStatus: 'in_review',
  milestones: [
    {
      id: 'documents_received',
      title: 'Documents Received',
      shortLabel: 'Docs Received',
      description: 'Checklist threshold reached; intake verified by firm staff.',
      completed: true,
      current: false,
      completedAt: '2026-03-15T09:12:00Z',
      details: '7 of 10 primary tax documents securely validated.',
    },
    {
      id: 'in_review',
      title: 'In Preparer Review',
      shortLabel: 'In Review',
      description: 'Marcus Vance, CPA is reviewing deductions and drafting Form 1040 & Schedule C.',
      completed: false,
      current: true,
      details: 'Awaiting remaining Form 1098 Mortgage Interest to finalize itemized deductions vs standard deduction.',
    },
    {
      id: 'filed',
      title: 'Filed with IRS & State',
      shortLabel: 'Filed',
      description: 'Electronic submission transmitted via IRS Modernized e-File (MeF).',
      completed: false,
      current: false,
      details: 'Ready for client electronic signature authorization (Form 8879) once review completes.',
    },
    {
      id: 'refund_payment',
      title: 'Refund or Payment Settled',
      shortLabel: 'Refund / Payment',
      description: 'IRS direct deposit confirmed or state voucher scheduled.',
      completed: false,
      current: false,
      details: 'Estimated federal refund tracking will appear here once IRS MeF accepts return.',
    },
  ],
  irsSubmissionId: 'IRS-MEF-2026-883910-NV',
  estimatedFederalRefund: 2840,
  estimatedStateRefund: 620,
  lastSyncedAt: 'Just now (Live Bridge: Karbon API)',
  notesFromPreparer: 'Elena, great progress on the W-2 and 1099-NEC. Please drop in your Form 1098 from Chase Mortgage when available so we can compare standard vs itemized deduction.',
};

export const INITIAL_CALENDAR_SLOTS: CalendarSlot[] = [
  { id: 'slot-1', preparerId: 'marcus_vance', date: '2026-03-25', time: '09:30 AM', durationMinutes: 20, available: true },
  { id: 'slot-2', preparerId: 'marcus_vance', date: '2026-03-25', time: '01:30 PM', durationMinutes: 20, available: true },
  { id: 'slot-3', preparerId: 'marcus_vance', date: '2026-03-26', time: '11:00 AM', durationMinutes: 20, available: true },
  { id: 'slot-4', preparerId: 'marcus_vance', date: '2026-03-26', time: '03:15 PM', durationMinutes: 30, available: true },
  { id: 'slot-5', preparerId: 'marcus_vance', date: '2026-03-27', time: '10:00 AM', durationMinutes: 20, available: true },
  { id: 'slot-6', preparerId: 'marcus_vance', date: '2026-03-30', time: '02:00 PM', durationMinutes: 20, available: true },
];

export const INITIAL_NOTIFICATIONS: NotificationRule[] = [
  {
    id: 'notif-1',
    type: 'deadline_alert',
    title: 'Filing Deadline Approaching',
    message: 'IRS Individual 1040 Deadline is April 15. Ensure all documents arrive before March 31 for timely filing.',
    triggerDate: 'Active (Daily sync)',
    channels: { push: true, email: true, sms: false },
    status: 'sent',
  },
  {
    id: 'notif-2',
    type: 'missing_document_nudge',
    title: 'Missing Document: Form 1098 Mortgage Interest',
    message: 'Marcus Vance, CPA is actively drafting your return and noted Form 1098 is still pending.',
    triggerDate: 'Scheduled: March 26 at 10:00 AM',
    channels: { push: true, email: true, sms: true },
    status: 'pending',
  },
  {
    id: 'notif-3',
    type: 'status_update',
    title: 'Intake Threshold Met (70%+ Complete)',
    message: 'Your file has progressed from "Intake" to "In Review with Marcus Vance, CPA".',
    triggerDate: 'March 15 at 09:12 AM',
    channels: { push: true, email: true, sms: false },
    status: 'sent',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-001',
    timestamp: '2026-03-23T11:15:20Z',
    actor: 'Client (Elena Rostova)',
    action: 'DOC_OCR_VERIFICATION',
    details: 'Uploaded 2025_W2_Apex_Technologies.pdf. Auto-classified as W-2 (Confidence 99%). Encrypted AES-256-GCM.',
    ipHash: 'SHA256: 7f81b...29',
    encryptionStandard: 'AES-256-GCM',
  },
  {
    id: 'log-002',
    timestamp: '2026-03-23T09:40:11Z',
    actor: 'System (Karbon Practice Bridge)',
    action: 'PRACTICE_MGMT_SYNC',
    details: 'Status synchronized: Milestone "In Preparer Review" set active by Marcus Vance, CPA.',
    ipHash: 'INTERNAL_GATEWAY',
    encryptionStandard: 'AES-256-GCM',
  },
  {
    id: 'log-003',
    timestamp: '2026-03-22T14:32:00Z',
    actor: 'Client (Elena Rostova)',
    action: 'MFA_CHALLENGE_SUCCESS',
    details: 'TOTP 6-digit Authenticator Token verified. Device fingerprint verified.',
    ipHash: 'SHA256: 7f81b...29',
    encryptionStandard: 'AES-256-GCM',
  },
  {
    id: 'log-004',
    timestamp: '2026-02-18T10:14:22Z',
    actor: 'Client (Elena Rostova)',
    action: 'ENGAGEMENT_ESIGN_RECORD',
    details: 'Engagement Letter & IRC § 7216 consent executed. Certificate ID: ESIGN-SV-2026-4409.',
    ipHash: 'SHA256: 7f81b...29',
    encryptionStandard: 'AES-256-GCM',
  },
];
